
name: ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Dockerhub login
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
            version: latest
      -
        name: Build dockerfile (with push)
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --file ./go-wecomchan/Dockerfile.architecture . \
            --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/wecomchan:2023.02
