
name: ci

on:

  push:

    branches:

      - 'wecom-2023.02'

  workflow_dispatch:

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      -

        name: Checkout

        uses: actions/checkout@v1

      -

        name: Set up QEMU

        uses: docker/setup-qemu-action@v1

      -

        name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v1

      -

        name: Dockerhub login

        env:

            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

        run: |

            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      -

        name: Build and push

        id: docker_build

        uses: docker/build-push-action@v2

        with:

          context: ./go-wecomchan

          push: true
          
          platforms: | 

             linux/amd64 

             linux/arm64 

             linux/arm/v7 

             linux/arm/v6 

             linux/386
             
          tags: huxuesen/wecomchan:2023.02
